**NUMPY**


In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
a[0:6]

array([1, 2, 3, 4, 5, 6])

In [4]:
a[2]

3

In [5]:
a[5]

6

In [6]:
a1 = np.array([1,2,3,5])
a2 = np.array([2,5,6,8])

In [7]:
a1+a2

array([ 3,  7,  9, 13])

In [8]:
a1-a2

array([-1, -3, -3, -3])

In [9]:
a1/a2

array([0.5  , 0.4  , 0.5  , 0.625])

In [10]:
a1*a2

array([ 2, 10, 18, 40])

In [11]:
a1 = np.array([1,2,3,5])
a2 = np.array([2,5,6,8,9])

In [12]:
a = np.array([[1,5],[3,4],[5,9],[9,1]])#it is a two dimension array
a

array([[1, 5],
       [3, 4],
       [5, 9],
       [9, 1]])

In [13]:
a = np.array([[1,5,9,5],[3,4,1,2],[5,9,5,7],[9,1,2,6]])
b = np.array([1,5,8,9])
y = a + b
print(y)

[[ 2 10 17 14]
 [ 4  9  9 11]
 [ 6 14 13 16]
 [10  6 10 15]]


In [14]:
y = a + b
print(y)

[[ 2 10 17 14]
 [ 4  9  9 11]
 [ 6 14 13 16]
 [10  6 10 15]]


In [15]:
a.size   #total no of items present

16

In [16]:
a.shape 

(4, 4)

In [17]:
# to print the dimension
a.ndim

2

In [18]:
a1 = np.array([1,2,3,5])  # it is oneD array
a1.ndim

1

In [19]:
a1.size

4

In [20]:
a.itemsize    # it gives us the bytes, how much it can occupy

4

In [21]:
a1.itemsize 

4

In [22]:
a.dtype

dtype('int32')

In [23]:
a1 = np.array([1,2,3,5],dtype=complex)
a1

array([1.+0.j, 2.+0.j, 3.+0.j, 5.+0.j])

In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
L = range(6)
L

range(0, 6)

In [26]:
L[2]

2

In [27]:
np.arange(1,6,2)

array([1, 3, 5])

In [28]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [29]:
a = np.array([[1,5],[3,4],[5,9],[9,1]])
a

array([[1, 5],
       [3, 4],
       [5, 9],
       [9, 1]])

In [30]:
a[2,1] #2-row and 1-column

9

In [31]:
a[2,0]

5

In [32]:
a[0:2,1] #0:2- rows 1 and 2  & 1 represent column

array([5, 4])

In [33]:
a[2]

array([5, 9])

In [34]:
a[-1]

array([9, 1])

In [35]:
a[-1,0:2]

array([9, 1])

In [36]:
a[:,0:1]

array([[1],
       [3],
       [5],
       [9]])

In [37]:
for cell in a.flat:
    print(cell)

1
5
3
4
5
9
9
1


In [38]:
a.reshape(2,4)

array([[1, 5, 3, 4],
       [5, 9, 9, 1]])

In [39]:
a.ravel()

array([1, 5, 3, 4, 5, 9, 9, 1])

In [40]:
a.min()

1

In [41]:
a.max()

9

In [42]:
a.sum()

37

In [43]:
a.mean()

4.625

In [44]:
a.var()

8.484375

In [45]:
a.std()

2.912795049432761

In [46]:
np.std(a)

2.912795049432761

In [47]:
np.sqrt(a)

array([[1.        , 2.23606798],
       [1.73205081, 2.        ],
       [2.23606798, 3.        ],
       [3.        , 1.        ]])

In [48]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])


In [49]:
a*b   #simply multiply

array([[ 5, 12],
       [21, 32]])

In [50]:
a.dot(b) #gives us cross product or matrix mutiplication

array([[19, 22],
       [43, 50]])

In [51]:
b=a>2
b

array([[False, False],
       [ True,  True]])

In [52]:
a[b]

array([3, 4])

In [53]:
import numpy as np


In [54]:
a = np.array([4,5,7,9,2,8])
b = a.reshape(3,2)
b

array([[4, 5],
       [7, 9],
       [2, 8]])

In [55]:
b.sum(axis=1)

array([ 9, 16, 10])

In [56]:
b.sum(axis=0)

array([13, 22])

In [57]:
np.sqrt(b)

array([[2.        , 2.23606798],
       [2.64575131, 3.        ],
       [1.41421356, 2.82842712]])

In [58]:
b.std()

2.4094720491334933

In [59]:
a=np.array([1,2,3])
b=np.array([1,2,3])
a*b

array([1, 4, 9])

In [60]:
a.dot(b)

14

In [61]:
np.dot(a,b)

14

In [62]:
a=([1,5,7],[9,0,1],[2,6,3])


In [63]:
b=np.linalg.inv(a)
b

array([[-0.0242915 ,  0.10931174,  0.02024291],
       [-0.10121457, -0.04453441,  0.25101215],
       [ 0.21862348,  0.01619433, -0.18218623]])

In [64]:
a = np.array([1,2,3])

In [65]:
a

array([1, 2, 3])

In [66]:
a[1]

2

In [74]:
b=np.array([[9,8,7],[6,5,4]],dtype='int64')

In [75]:
b

array([[9, 8, 7],
       [6, 5, 4]], dtype=int64)

In [76]:
b.ndim

2

In [77]:
b.shape

(2, 3)

In [78]:
b.dtype

dtype('int64')

In [79]:
print(type(b))

<class 'numpy.ndarray'>


In [80]:
b.itemsize #as int64 occupy 8 bytes

8

In [84]:
a.itemsize #as int32 occupy 4 bytes

4

In [85]:
b.size

6

In [89]:
a=np.array([[2,3,4,5],[6,5,4,6],[1,2,5,8]])

In [91]:
a.ndim

2

In [95]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [102]:
np.linspace(-51,51,100)

array([-51.        , -49.96969697, -48.93939394, -47.90909091,
       -46.87878788, -45.84848485, -44.81818182, -43.78787879,
       -42.75757576, -41.72727273, -40.6969697 , -39.66666667,
       -38.63636364, -37.60606061, -36.57575758, -35.54545455,
       -34.51515152, -33.48484848, -32.45454545, -31.42424242,
       -30.39393939, -29.36363636, -28.33333333, -27.3030303 ,
       -26.27272727, -25.24242424, -24.21212121, -23.18181818,
       -22.15151515, -21.12121212, -20.09090909, -19.06060606,
       -18.03030303, -17.        , -15.96969697, -14.93939394,
       -13.90909091, -12.87878788, -11.84848485, -10.81818182,
        -9.78787879,  -8.75757576,  -7.72727273,  -6.6969697 ,
        -5.66666667,  -4.63636364,  -3.60606061,  -2.57575758,
        -1.54545455,  -0.51515152,   0.51515152,   1.54545455,
         2.57575758,   3.60606061,   4.63636364,   5.66666667,
         6.6969697 ,   7.72727273,   8.75757576,   9.78787879,
        10.81818182,  11.84848485,  12.87878788,  13.90

In [104]:
a=([1,2,3,4,5,6,7,8,9])
b=np.reshape(a,(3,3))

In [105]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
b.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
b.max()

9

In [129]:
a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(2,2,2)

In [130]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [132]:
b.sum(axis=0)

array([[ 6,  8],
       [10, 12]])

In [133]:
b.sum(axis=1)

array([[ 4,  6],
       [12, 14]])

In [134]:
b.sum(axis=2)

array([[ 3,  7],
       [11, 15]])

In [120]:
q=np.array([1,2,3])
w=np.array([5,6,7])

In [122]:
q.dot(w)

38

In [123]:
b

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [127]:
b[2,0]

array([7, 8, 9])

In [135]:
np.full((2,2),100)

array([[100, 100],
       [100, 100]])

In [142]:
np.random.randint((1,10,5),size=(3,2))

ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [146]:
a=np.ones((5,5),dtype='int32')

In [147]:
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [148]:
b=np.zeros((3,3),dtype='int32')

In [149]:
b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [153]:
b[1,1]=9
b

array([[0, 0, 0],
       [0, 9, 0],
       [0, 0, 0]])

In [156]:
a[1:4,1:4]=b

In [157]:
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])